#!/bin/bash
#
# Bash wrapper to create vocabulary
# from (sorted) word frequency count file.
#
#
###############################################################################

log() {
	printf "`date +%c` - $*\n" >&2
}
usage() {
	printf "USAGE: $(basename $0) [<max_terms>] < infile > outfile\n" >&2
	exit 1
}

###############################################################################

# Max terms in vocabulary
MAX_TERMS=65535

if [ "$#" -gt 0 ];
then
    MAX_TERMS=$1
    shift
fi

log "Creating vocabulary from sorted wfreq file. MAX_TERMS == ${MAX_TERMS}"

cat $* | \
	awk -F"\t" '{print $2}' | \
	head -n ${MAX_TERMS}

log "All done"
