#!/bin/bash
#
# Bash wrapper to create vocabulary
# from word frequency count file.
#
#
###############################################################################

log() {
	printf "`date +%c` - $*\n" >&2
}
usage() {
	printf "USAGE: $(basename $0) -m <max_terms> < infile > outfile\n" >&2
	exit 1
}

###############################################################################

# Max terms in vocabulary
MAX_TERMS=65535

# key to sort by (e.g frequency column index)
KEY=1

log "Creating vocabulary from sorted wfreq file"

cat $* | \
	awk -F"\t" '{print $2}' | \
	head -n ${MAX_TERMS}

log "All done"
